### ISSUE TITLE
Different r^2 values score

### ISSUE THREAD

**Issue by AFilipaAlmeida** [sustainable-processes/summit#140]
* Operating System: Windows 10
* Python version: Python 3.7.10 through anaconda
* summit version used: 0.8.0rc1

### Description

Different r^2 values were obtained in parity plot and scores=exp.scores()

### What I Did

After trained the experimentalemulator I obtained different r^2 values for test in parity.plot and scores=emul.test().

![image](https://user-images.githubusercontent.com/74240882/119343034-cb2bfb80-bc8d-11eb-929a-2f927f2b0ed4.png)

Do you know why these results are different? with code for scores I have ten values for r^2 and MSE but I only have eight objectives. What it's wrong in my code?

**Comment by marcosfelt** [comment]
I believe the code in test is wrong. I will check this.

**Comment by marcosfelt** [comment]
Okay, I see the issue. The `test` code averages over the predictors, so those are scores averaged over all objectives for each of the 10 predictors (because of 10-fold cross-validation). The parity_plot code gives the scores for each objective averaged over the predictors. I will add documentation clarifying this.
