### ISSUE TITLE
Possible incorrect variables

### ISSUE THREAD

**Issue by JohanvdWesthuizen** [sustainable-processes/summit#141]
* summit version used: 0.8.1

### Description

The variable inside the **snar benchmark** might be incorrectly assigned.

[https://github.com/sustainable-processes/summit/blob/054db4e86a2f3b71919fd02ef99ee3c02fb2948f/summit/benchmarks/snar.py#L117-L118](url)
Line 117 & 118 is:
```
C1_0 = 2.0 # reservoir concentration of 1 is 1 M = 1 mM
C2_0 = 4.2 # reservoi concentration of 2 is 2 M = 2 mM
```
Should it not be:  
```
C1_0 = 1.0 # reservoir concentration of 1 is 1 M = 1 mM
C2_0 = 2.0 # reservoir concentration of 2 is 2 M = 2 mM
```

I might be misunderstanding the logic, but thought I should double-check...

**Comment by marcosfelt** [comment]
Hi Johan, I have no idea how that crept in. Thankfully, it shouldn't have a significant impact on the results, since the kinetics are driven by the decision variables instead of the reservoir concentrations; see the contour plots below. Would you be able to submit a PR with this change?

![compare_initial_concentrations](https://user-images.githubusercontent.com/25933639/119504641-16184280-bd64-11eb-86b4-6ed0baa50f88.png)
