### ISSUE TITLE
Noisy evaluations

### ISSUE THREAD

**Issue by jduerholt** [sustainable-processes/summit#73]
Add adjustable noise level to the synthetic benchmark problems.

**Comment by marcosfelt** [comment]
See the SnarBenchmark for an example of how this could be implemented.

However, maybe we can create a wrapper around the run method in experiments that automatically adds noise?

**Comment by jduerholt** [comment]
A general wrapper to add additive noise, sampled from some distribution (normal as simplest case), seems for me the best case. Maybe one could also specify different noise levels for every objective?

**Comment by marcosfelt** [comment]
I like thi

> A general wrapper to add additive noise, sampled from some distribution (normal as simplest case), seems for me the best case. Maybe one could also specify different noise levels for every objective?

I like this idea. Maybe something like this?

```python
exp = SnarBenchmark()
noise = Noise(level=dict(sty=2.5, e_factor=2.5), experiment=exp)
```
One challenge with implementing the noise this way is that it doesn't really reflect where the noise shows up in experiments. In the [SnarBenchmark](https://github.com/sustainable-processes/summit/blob/59012ad91bb28fd1d0870bcd5802824a83ade93f/summit/benchmarks/snar.py#L128), I include noise in the concentration because that's where you'd see noise in an actual experiment (e.g., random error from an HPLC measurment). That then propagates through to the objectives of space time yield and E-factor.

**Comment by marcosfelt** [comment]
I'm closing this issue since it's been open for a while.
