### ISSUE TITLE
TSEMO Convergence Error

### ISSUE THREAD

**Issue by m-jeraal** [sustainable-processes/summit#92]
* Operating System: Windows 10
* Python version: Anaconda 3.8 on Pycharm
* summit version used: Various

### Description

Using TSEMO to generate conditions for experimental closed loop optimisation.

### What I Did

Attempted to run TSEMO using the attached .script and data. On Summit version 0.4, the system appeared to work fine. Running 0.6 onwards, I received the attached error.

[sampledata.csv.txt](https://github.com/sustainable-processes/summit/files/6015573/sampledata.csv.txt)
[tempsummit.py.txt](https://github.com/sustainable-processes/summit/files/6015563/tempsummit.py.txt)
[TSEMOError.txt](https://github.com/sustainable-processes/summit/files/6015728/TSEMOError.txt)

**Comment by marcosfelt** [comment]
There are multiple things going on here:
1. 0.4.0 works very nicely but unfortunately misses a key step in the TSEMO algorithm: thompson sampling. It basically uses the mean predictions of the GPs instead of sampling a deterministic function. It's interesting that you say that 0.4.0 works well for you because multiple people independently told me that eschewing acquisition functions / thompson sampling has worked quite well for them in other BO algorithms. That said, without thompson sampling, it's not TSEMO.
2. The bug in 0.8.0rc0 is due to GP training. Somewhere between 0.4.0 and now,  I added priors to the hyperparameters  of the GP, just as done in the Matlab version. These extra constraints are important to performance, but are somehow causing the GP training to be inconsistent. I confirmed this by running your sample code without the hyperparameter priors; it ran smoothly without all the warnings or errors.  This training boondoggle is ultimately a problem with GPy, the package we're using for training GPs.  I am thinking about moving from GPy to GPytorch, which we've found to work a lot better in some other projects (e.g., multitask BO).
